### PR TITLE
feat: added number of open issues

### LINKED ISSUE #153: Show the number of issues too inside the card

### PR DESCRIPTION
**Pull request by Keith-Web3**
Fixes #153 
I've noticed that the GitHub API's `open_issues_count` field currently includes both the count of open Issues and open Pull Requests. This is because GitHub counts PRs as issues in their system. I hope this would not be a problem?

### CODE REVIEW

**Comment by max-programming** [comment]
Also can you fix this problem? And also show the open PRs
image

**Comment by Keith-Web3** [comment]
Alright, I'll work on the tooltip. 
For the open PRs, GitHub's API does not provide the number of open PRs

**Comment by Keith-Web3** [comment]
@max-programming I've adjusted the tooltip

**Comment by max-programming** [comment]
> Alright, I'll work on the tooltip. 
> For the open PRs, GitHub's API does not provide the number of open PRs

Then I think it's better to put the number of issues in the center as there's nothing beside it

**Comment by Keith-Web3** [comment]
Do you mean putting the three buttons in one line? Doing that would make it unresponsive and it's not going to look nice on small screens.

**Comment by max-programming** [comment]
@Keith-Web3 No. Make it like this
image

**Comment by Keith-Web3** [comment]
@max-programming Done.

**Comment by max-programming** [comment]
@Keith-Web3 Looks good! Just a few more changes. There is too much margin around the first two boxes and the last box looks a lot compressed

image

**Comment by Keith-Web3** [comment]
Sadly, there's no way to get rid of the extra margin as the browser has no way of knowing when items are wrapping. Also, the buttons adjust to the size of their content. This is the best way to ensure responsiveness and it's why the issues button appears small.

**Comment by max-programming** [comment]
@Keith-Web3 Maybe you can increase the width or min width of that card.
That might fix it and reduce the whitespace

**Comment by Keith-Web3** [comment]
Alright then, I'll make another pull request. Using grid won't work but I've got one last idea.

**Comment by janaSunrise** [comment]
Hey! It all looks good. Imo, it's better to have it this way though.

Screenshot 2023-10-09 at 7 59 55 PM

And the current font size when hovered doesn't really go with it. Making it centered + a bit small would be better with it.

Screenshot 2023-10-09 at 8 00 54 PM

**Comment by max-programming** [comment]
@janaSunrise Having all three side by side will increase the width of the card significantly, won't it?

**Comment by Keith-Web3** [comment]
@max-programming Yes it would. There's been a lot of back and forth on just the button alignment 🥲

**Comment by max-programming** [comment]
@all-contributors please add @Keith-Web3 for ideas, code

**Comment by janaSunrise** [comment]
> @janaSunrise Having all three side by side will increase the width of the card significantly, won't it?

Yup, but we can make it smaller, don't you think?

**Pull request merged**
