### PR TITLE
Updates to button and overall daisyUI theme

### PR DESCRIPTION
**Pull request by Mikkel-T**
Change border-radius on buttons to 2px
Change daisyUI theme to dark as it looks more like current hacktoberfest theme
Change border width on contributor card buttons so the border is visible

### CODE REVIEW

**Comment by max-programming** [comment]
Looks amazing! Thanks @Mikkel-T 

Can you also fix these two buttons and make them `flex-col` on mobile



[Page link](https://hacktoberfest-projects-git-fork-mikkel-t-62fb27-max-programming.vercel.app/repos/python?p=2)

**Comment by Mikkel-T** [comment]
@max-programming should be done now!

**Comment by max-programming** [comment]
Just a little change.

When on mobile, these also should be `flex-col`.

 

Sorry to demand so much 😅

**Comment by Mikkel-T** [comment]
Of course, this should address that!

**Pull request merged**
