### PR TITLE
created custom 404 page

### PR DESCRIPTION
**Pull request by syprogrammer**

### CODE REVIEW

**Comment by syprogrammer** [comment]
@max-programming i have created 404 page review it

**Comment by max-programming** [comment]
Looks great! @syprogrammer . Can you make the button the same as other buttons too please?

**Comment by yash206** [comment]
please allow me to share my 404 error page

**Comment by syprogrammer** [comment]
@max-programming i have changed button color and file name to tsx

**Comment by max-programming** [comment]
@yash206 yes please. Do open a PR for yours 🙂

**Comment by max-programming** [comment]
@syprogrammer Could you change the Image components to normal img tags. And instead of importing images just use the name with a slash and without the `public` in front of it. Like this

```html
<img src="/name.png" />
```

**Comment by janaSunrise** [comment]
This looks good, but please fix the conflicts! then, I'll approve this.

**Pull request closed without merging**
