### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by donno2048**

### CODE REVIEW

**Comment by max-programming** [comment]
@donno2048 Can you change the images to the latest Hacktoberfest images?

You can download them from [here](https://hacktoberfest.com/events/#organizers)

**Comment by max-programming** [comment]
@donno2048 Yeah so downloading from the [brand guidelines](https://hacktoberfest.com/events/#organizers) will give you the original files

**Comment by donno2048** [comment]
On the Hacktoberfest site there's only an SVG and in the Figma design I cannot download from mobile...

**Comment by max-programming** [comment]
@donno2048 I'll put the accepted label on this because #154 is also about the same. Thanks

By the you don't need to use the figma, the assets can be downloaded from here
image

**Comment by donno2048** [comment]
If you put the accepted label because of Hacktoberfest it's fine, I'm not participating, but thanks!

**Comment by max-programming** [comment]
No problems @donno2048
I did it assuming majority people are participating and this project is also related to HF.

**Comment by max-programming** [comment]
No problems @donno2048
I did it assuming majority people are participating and this project is also related to HF.

**Pull request closed without merging**
