### PR TITLE
Report Button Added

### PR DESCRIPTION
**Pull request by Mohit030802**
This PR is in continuation to #102 which was closed by mistake while I was solving a merger conflict. I have added the Report button and a Modal pops up when you click the report button which is on the right top corner of the repo card.                                    
 
 it is an amazing project and I am looking forward to contributing more to this project.
 
 Final result
s1

### CODE REVIEW

**Comment by max-programming** [comment]
Also the buttons and the textarea should be from daisyui itself. Can you use their styles?

**Comment by Mohit030802** [comment]
Yeah Sure, I will use it 👍

**Comment by Mohit030802** [comment]
I have edited the textarea and the button using [DaisyUI](https://daisyui.com) 
image

**Comment by max-programming** [comment]
Thanks a lot Mohit!

@all-contributors please add @Mohit030802 code, ideas

**Comment by Mohit030802** [comment]
Looking forward to contributing more to this project 😊.

**Comment by max-programming** [comment]
@Mohit030802 Because you force-pushed from `main` to your `main`, all the commits and code got overwritten.

I recovered all of it from [here ](https://github.com/max-programming/hacktoberfest-projects/compare/64ae688fb789e45d28a68eb3a0a1f437cf964e47..3d08303276091e4e202514224b77b054f2490ba7)but force pushing can cause more serious problems

**Comment by Mohit030802** [comment]
Hi @max-programming, I would like to extend my sincere apologies for the error that occurred recently. It was entirely accidental and not at all intentional. I deeply regret any inconvenience this may have caused you. I want to express my gratitude for bringing this matter to my attention. Your feedback is important to me, and I will be more cautious in my contributions moving forward.

Thank you for your understanding.

**Comment by max-programming** [comment]
No issues @Mohit030802 

I also didn't know the consequences hence the problem. I just wanted to bring it to your attention so that there are no future mistakes 🙂

**Comment by Mohit030802** [comment]
Yeah, I will take care of it next time.

**Pull request merged**
