### PR TITLE
Fixes Issue #129: Stars filter not getting reset on updating the language

### PR DESCRIPTION
**Pull request by NishidhJain**
This fixed issue #129

@max-programming Please have a look at it.

### CODE REVIEW

**Comment by max-programming** [comment]
@NishidhJain I think this is not the right solution. We actually want to keep all the previous query params.
So it's better that when the language is changes, keep all the previous query params (stars as well) and just change the path

**Comment by NishidhJain** [comment]
@max-programming In my opinion if we are the updating the language, then we should see all the repos for that language and not with the previous filter because the old filters might not be applicable for new language. In that case the user will see 404 page & think that there are no repos for newly selected language until he/she sees that URL contains some filters as well and removing them will show some repos which is hard to detect.

Please share your views on this. Thanks!

**Comment by NishidhJain** [comment]
Hey @janaSunrise, please share your thoughts on this, would be happy to know what do you think

**Comment by janaSunrise** [comment]
LGTM! Has it been tested?

**Review by janaSunrise — APPROVED** [review]

**Comment by NishidhJain** [comment]
Thanks for the review @janaSunrise. Can you let me know the meaning of LGTM?

@max-programming Can we merge this PR now

**Comment by max-programming** [comment]
Thanks @NishidhJain!

Also LGTM means "Looks good to me"

**Pull request merged**
