### PR TITLE
Add option to sort by "Most help wanted issues"

### PR DESCRIPTION
**Pull request by Mikkel-T**
Adds an option to sort by "Most help wanted issues"

### CODE REVIEW

**Comment by janaSunrise** [comment]
Thank you so much for the PR, but it seems the list is getting longer, and It might not look good on all screens, Can you add scrolling so it's better? Thank you!

**Comment by Mikkel-T** [comment]
Added scrolling and gave it a height of `h-64`, hope it's good!

**Comment by max-programming** [comment]
That is a lot better @Mikkel-T! Can you also increase the width a little bit to fit everything in one line?
image

**Comment by max-programming** [comment]
That's great! Thank you!

**Comment by max-programming** [comment]
@all-contributors please add @Mikkel-T for code, design

**Pull request merged**
