### PR TITLE
Report Button added

### PR DESCRIPTION
**Pull request by Mohit030802**
I have added a report button to each repository card. When a user clicks on it, a simple pop-up will open, prompting them to provide a reason for the report. Once the user has filled in the details, the report will be submitted, and a response will be sent to your email address for review purposes.
s3

### CODE REVIEW

**Comment by max-programming** [comment]
Thanks! Can you please explain the form submit event and how it works?

**Comment by Mohit030802** [comment]
When a user submits the reason for the report via Form Spree, it sends you an email. Form Spree is a web platform linked to your email. Currently, it is linked to my email, but if you agree, I will change it to yours.

**Comment by max-programming** [comment]
Sure @Mohit030802 change it to `contact@usmans.me` and also, can you make the UI a little more better?
Following https://daisyui.com

**Comment by max-programming** [comment]
Sure @Mohit030802 change it to `contact@usmans.me` and also, can you make the UI a little more better?
Following https://daisyui.com

**Comment by Mohit030802** [comment]
Sure I will do it 👍

**Comment by max-programming** [comment]
@Mohit030802 I feel like using formspree is an overkill as it has a paid plan and only allows 50/submissions per month

Instead just make the modal and the form and I will do the implementation of some database integration as well

**Comment by Mohit030802** [comment]
@max-programming Yeah formspree is paid and has limited submissions per month. shall I go for MongoDB or any other DB?

**Comment by max-programming** [comment]
I'll go ahead and configure supabase and all that. So don't worry about the backend.

**Comment by Mohit030802** [comment]
Hi, @max-programming I have changed the UI a little bit referencing [DaisyUi.](https://daisyui.com) . The report modal is in src/ReportModal. If you need any changes please let me know

s1

**Comment by max-programming** [comment]
Awesome! A few more changes

- Move the note below the title of the modal
- Add a placeholder on the input and make it required

**Comment by Mohit030802** [comment]
@max-programming By mistake I closed the PR. I have made the changes, but I can't understand how all this happened. What should I do? Help me

**Pull request closed without merging**
