### PR TITLE
Changed some styles to incorporate hacktoberfest 2021 colors

### PR DESCRIPTION
**Pull request by AnishDe12020**
I have changed the colors to match the hacktoberfest 2021 colors and also styled the scrollbar. I have also got rid of unused code

### CODE REVIEW

**Comment by max-programming** [comment]
This seems a lot better! Thank you. There are some things that need to fixed though. The language name is impossible to see
image

**Comment by max-programming** [comment]
Also for the hover effect of this button, you can choose the darker variant of orange (#b53a25)
image

**Comment by AnishDe12020** [comment]
> Also for the hover effect of this button, you can choose the darker variant of orange (#b53a25) image
> 
> Also the current orange colour is a little bit hard on the eyes. You can make it more soothing by changing it a little.

Done!

**Comment by max-programming** [comment]
Change the current orange colour to this one which makes it look better on dark background - `rgb(198, 57, 0)`

**Comment by AnishDe12020** [comment]
> rgb(198, 57, 0)

Done!

**Comment by max-programming** [comment]
Now it looks darker 😂. I finally chose a colour which is best of all: `#ff5724` (Tested)

Also make sure to change this to the main colour as it is not visible
image

**Comment by AnishDe12020** [comment]
> Now it looks darker joy. I finally chose a colour which is best of all: `#ff5724` (Tested)
> 
> Also make sure to change this to the main colour as it is not visible image

Oh I didn't notice that, I have fixed it and changed the primary color

**Comment by max-programming** [comment]
@all-contributors please add @AnishDe12020 for design

**Pull request merged**
