### PR TITLE
#150 Search text color

### PR DESCRIPTION
**Pull request by malik-vishu**
| Before | After |
| --- | --- |
| finder_proj_missing_search | finder_proj_missing_search_after |

@max-programming Please Check

### CODE REVIEW

**Comment by max-programming** [comment]
@malik-vishu Instead of neutral, can you use one of the brighter colors from the tailwind config? Thanks!

**Comment by malik-vishu** [comment]
@max-programming Please check

**Comment by malik-vishu** [comment]
@max-programming Files are same why is it showing conflict?

**Comment by malik-vishu** [comment]
@max-programming Files are same why is it showing conflict?

**Pull request closed without merging**
