### PR TITLE
Refactoring/add GitHub action 

### PR DESCRIPTION
**Pull request by jpdias**
- Fix ESLint warnings
- Format files
- Add GitHub Action for checking linting and format of new PRs

### CODE REVIEW

**Comment by max-programming** [comment]
@jpdias Can you only keep the GitHub action and remove the other changes? Especiallt the `Image` component. I kept it normal `img` on purpose

**Comment by jpdias** [comment]
@max-programming I've made the requested change regarding Image (and ignored the eslint rule).

**Comment by max-programming** [comment]
Thank you @jpdias

**Comment by max-programming** [comment]
Just let @janaSunrise review it once and we'll merge it

**Review by janaSunrise — APPROVED** [review]
LGTM

**Pull request merged**
