### PR TITLE
fix going to empty page

### PR DESCRIPTION
**Pull request by vinmaster**
Closes: https://github.com/max-programming/hacktoberfest-projects/issues/71

### CODE REVIEW

**Comment by max-programming** [comment]
Thanks a lot for this @vinmaster!

Could you also make the page 404 if there are 0 repos on that page?

I guess you can use `notFound: true` if the array length is 0

**Comment by vinmaster** [comment]
Updated, please have a look!

**Comment by max-programming** [comment]
@vinmaster doesn't seem to work that way. Because `total_items` isn't doesn't return pagination based items. Maybe try `repos.items.length` and check if that is less than 1.

**Comment by vinmaster** [comment]
Ah okay. Got it. It should be updated now

**Comment by max-programming** [comment]
@all-contributors please add @vinmaster for code

**Pull request merged**
