### PR TITLE
style: add border of search button #112

### LINKED ISSUE #112: style: add border/bg of search button
currently, if we hover over the button it will show a bg but we should add a border/bg. I want to work on this issue. 
image

### PR DESCRIPTION
**Pull request by priyankarpal**
fixes #112

- added simple white border to look simple & minimalist

### CODE REVIEW

**Comment by max-programming** [comment]
Thanks! It'd be better if you could also make the padding same on all sides on the button to make it look better
image

**Comment by priyankarpal** [comment]
here it's looking fine 
image

**Comment by max-programming** [comment]
So just the text isn't centered. Maybe adding a `text-center` or `flex items-center` might fix it.

**Comment by priyankarpal** [comment]
> So just the text isn't centered. Maybe adding a `text-center` or `flex items-center` might fix it.

not working :)

**Pull request merged**
