### PR TITLE
chore(dep): migrate to pnpm #115

### LINKED ISSUE #115: chore(dep): migrate to `pnpm`
Currently, we are using `npm` for this project, but `npm` has a few problems. 

`pnpm`:

- Saves disk space by not duplicating packages.
- Faster installations due to shared packages.
- Reduces bandwidth usage by downloading packages once.
- Uses efficient linking for quicker operations.
- Ensures better project isolation.

`npm`:

- May consume more disk space due to duplicated packages.
- Slower installations compared to pnpm.
- May use more bandwidth by downloading packages for each project.
- Performs standard package installations.

pnpm docs: https://pnpm.io/benchmarks

### Note: I want to work on this issue

### PR DESCRIPTION
**Pull request by priyankarpal**
- deleted lock file & added to .gitignore
- added pnpm-workspace file
- added "preinstall": "npx only-allow pnpm" to package.json

fixes #115

### CODE REVIEW

**Comment by priyankarpal** [comment]
@max-programming we don't need the lock file you can delete

**Comment by max-programming** [comment]
Actually we do need the lockfiles. Remove them from gitignore. Pushing lockfiles is important

**Comment by max-programming** [comment]
Just some conflicts left to fix

**Comment by priyankarpal** [comment]
> Just some conflicts left to fix

yeah, I deleted package-lock.json file so that's why

**Pull request merged**
