### PR TITLE
Issue #148: Improve overall readability for Repo cards

### PR DESCRIPTION
**Pull request by NishidhJain**
This resolves issue #148

### CODE REVIEW

**Comment by max-programming** [comment]
Looks much better than before @NishidhJain 👏

Can you just pull in the changes from `main` so I can proceed with merging

**Comment by NishidhJain** [comment]
Hey @max-programming, have pulled the changes from main branch.

**Comment by max-programming** [comment]
The only issue I see right now is this overflow of text. It's not a problem on `main`
image

**Comment by NishidhJain** [comment]
@max-programming Fixed the issue, please have a look

**Comment by prithvi2k2** [comment]
@max-programming @NishidhJain  on default mode(light), people are seeing this... @NishidhJain please develop using static fixed colors for every element... it should not be dependent on light/dark mode of client
image

**Pull request merged**
