### PR TITLE
#98 - Edit color contrast ratio to address accessibility concerns 

### PR DESCRIPTION
**Pull request by malik-vishu**
Hi @max-programming Check it out. It's done.
Accept it after 30 September please.
Before
</img>   
After
</img>

Before
</img>   
After
</img>

Before
</img>   
After
</img>

### CODE REVIEW

**Comment by kantakshay** [comment]
There are two icons on the navbar top right that are not visible due to color ratio, I think you should look into it.

**Comment by malik-vishu** [comment]
@kantakshay Already done
finder_proj_after4

**Comment by max-programming** [comment]
Let's make this one of the bright colors defined in the `tailwind.config.js`. The color you have defined also blends in the background which does not look that visible
image

**Comment by malik-vishu** [comment]
@max-programming Ok no problem

**Comment by malik-vishu** [comment]
@max-programming If I write this-> text-from-2023-bavarian-gold-2 ,in the className, it isn't working. Could you help me out here?
This is working-> text-[#d2b863]. Should I do like this?

**Comment by max-programming** [comment]
@malik-vishu That is because you write **from** in `text-` styling. You can't use gradient on text color. Also use the `manga` color not gold. Use it like `text-manga....`

**Comment by malik-vishu** [comment]
@max-programming 
Now?
This is manga 3
image

**Comment by max-programming** [comment]
Yeah. Looks fine 👍

**Comment by malik-vishu** [comment]
@max-programming Please check color changes pushed.

**Comment by max-programming** [comment]
Thank you! Merged 🤝

**Comment by max-programming** [comment]
@all-contributors please add @malik-vishu for code, design

**Comment by malik-vishu** [comment]
@max-programming Thank you😄 for the opportunity.

**Pull request merged**
