### PR TITLE
style: modify search icon hover behavior

### PR DESCRIPTION
**Pull request by nabarvn**
I've made some changes to the `SearchIcon` svg towards resolving issue #170.

My suggestion:

```diff
- className="w-6 h-6"
+ className="w-6 h-6 group-hover:stroke-2023-bavarian-gold-3"
```

Screenshot for reference:

Submit Button Style Fix

### CODE REVIEW

**Comment by max-programming** [comment]
Looks good! But I think it will look better with this one change

- Add the golden border like the input to the button

**Comment by huzaifaalmesbah** [comment]
Looks Good.

**Comment by nabarvn** [comment]
> @nabarvn Looks good! But I think it will look better with this one change
> 
> * Add the golden border like the input to the button when not hovered

Sure thing!

**Comment by nabarvn** [comment]
Changes applied:

```diff
- border-2023-manga-3
+ border-2023-bavarian-gold-2
```

Screenshot for reference:

Submit Button Border Color Fix

**Comment by max-programming** [comment]
Thank you Nabarun!

**Pull request merged**
